/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as SensitiveNewRouteImport } from './routes/sensitive.new'
import { Route as ReportNewRouteImport } from './routes/report.new'
import { Route as ChatConnectionIdRouteImport } from './routes/chat.$connectionId'
import { Route as MatchesIdVerifyRouteImport } from './routes/matches.$id.verify'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitiveNewRoute = SensitiveNewRouteImport.update({
  id: '/sensitive/new',
  path: '/sensitive/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportNewRoute = ReportNewRouteImport.update({
  id: '/report/new',
  path: '/report/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConnectionIdRoute = ChatConnectionIdRouteImport.update({
  id: '/chat/$connectionId',
  path: '/chat/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdVerifyRoute = MatchesIdVerifyRouteImport.update({
  id: '/matches/$id/verify',
  path: '/matches/$id/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broadcast': typeof BroadcastRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/tags': typeof TagsRoute
  '/chat/$connectionId': typeof ChatConnectionIdRoute
  '/report/new': typeof ReportNewRoute
  '/sensitive/new': typeof SensitiveNewRoute
  '/matches/': typeof MatchesIndexRoute
  '/matches/$id/verify': typeof MatchesIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broadcast': typeof BroadcastRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/tags': typeof TagsRoute
  '/chat/$connectionId': typeof ChatConnectionIdRoute
  '/report/new': typeof ReportNewRoute
  '/sensitive/new': typeof SensitiveNewRoute
  '/matches': typeof MatchesIndexRoute
  '/matches/$id/verify': typeof MatchesIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broadcast': typeof BroadcastRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/tags': typeof TagsRoute
  '/chat/$connectionId': typeof ChatConnectionIdRoute
  '/report/new': typeof ReportNewRoute
  '/sensitive/new': typeof SensitiveNewRoute
  '/matches/': typeof MatchesIndexRoute
  '/matches/$id/verify': typeof MatchesIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/broadcast'
    | '/dashboard'
    | '/demo'
    | '/map'
    | '/profile'
    | '/tags'
    | '/chat/$connectionId'
    | '/report/new'
    | '/sensitive/new'
    | '/matches/'
    | '/matches/$id/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/broadcast'
    | '/dashboard'
    | '/demo'
    | '/map'
    | '/profile'
    | '/tags'
    | '/chat/$connectionId'
    | '/report/new'
    | '/sensitive/new'
    | '/matches'
    | '/matches/$id/verify'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/broadcast'
    | '/dashboard'
    | '/demo'
    | '/map'
    | '/profile'
    | '/tags'
    | '/chat/$connectionId'
    | '/report/new'
    | '/sensitive/new'
    | '/matches/'
    | '/matches/$id/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BroadcastRoute: typeof BroadcastRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  TagsRoute: typeof TagsRoute
  ChatConnectionIdRoute: typeof ChatConnectionIdRoute
  ReportNewRoute: typeof ReportNewRoute
  SensitiveNewRoute: typeof SensitiveNewRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  MatchesIdVerifyRoute: typeof MatchesIdVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitive/new': {
      id: '/sensitive/new'
      path: '/sensitive/new'
      fullPath: '/sensitive/new'
      preLoaderRoute: typeof SensitiveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/new': {
      id: '/report/new'
      path: '/report/new'
      fullPath: '/report/new'
      preLoaderRoute: typeof ReportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$connectionId': {
      id: '/chat/$connectionId'
      path: '/chat/$connectionId'
      fullPath: '/chat/$connectionId'
      preLoaderRoute: typeof ChatConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id/verify': {
      id: '/matches/$id/verify'
      path: '/matches/$id/verify'
      fullPath: '/matches/$id/verify'
      preLoaderRoute: typeof MatchesIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BroadcastRoute: BroadcastRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  TagsRoute: TagsRoute,
  ChatConnectionIdRoute: ChatConnectionIdRoute,
  ReportNewRoute: ReportNewRoute,
  SensitiveNewRoute: SensitiveNewRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  MatchesIdVerifyRoute: MatchesIdVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
